{application,waiters,
             [{description,"Waiters Application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{waiter_sup,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[waiter_fsm,waiter_mng,waiter_sup]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
